[package]
name = "cli_req_refiner"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
my_config.workspace = true
my_proxy.workspace = true
anyhow.workspace = true
chrono.workspace = true
mimalloc.workspace = true
salvo.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
bytes.workspace = true
http.workspace = true
hyper.workspace = true
