[package]
name = "my_handler"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
my_config.workspace = true
my_optimization.workspace = true
anyhow.workspace = true
bytes.workspace = true
flate2.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
salvo.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
