[package]
name = "my_handler"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
my_config.workspace = true
my_proxy.workspace = true
anyhow.workspace = true
salvo.workspace = true
tracing.workspace = true

[dev-dependencies]
bytes.workspace = true
hyper.workspace = true
tokio.workspace = true
